name: Build Android APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Grant execute permission for gradlew
      run: chmod +x "Oyuncu Kariyeri Oyunu/android-app/gradlew"

    - name: Build Debug & Release APK
      run: |
        cd "Oyuncu Kariyeri Oyunu/android-app"
        ./gradlew assembleRelease assembleDebug --stacktrace

    - name: Upload Release APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Rise-Of-Greatness-Release-APK
        path: Oyuncu Kariyeri Oyunu/android-app/app/build/outputs/apk/release/*.apk

    - name: Upload Debug APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Rise-Of-Greatness-Debug-APK
        path: Oyuncu Kariyeri Oyunu/android-app/app/build/outputs/apk/debug/*.apk
